export const weatherTheme = {
  "01d": {
    icon: "https://i.ibb.co/xKzG7FKd/sunny-icon.png",
    description: "Sun weather icon",
    background: "https://i.ibb.co/KzcBHhX1/clear-sky.gif",
    colour: "#3d89c0ff",
  },
  "01n": {
    icon: "https://i.ibb.co/sdCj56dW/clear-night-icon.png",
    description: "Crescent moon weather icon",
    background: "https://i.ibb.co/fYj3ZGzt/clear-night-sky.gif",
    colour: "#2C3E50",
  },
  "02d": {
    icon: "https://i.ibb.co/yBFzQgXD/sunny-cloud-icon.png",
    description: "Sunny cloud weather icon",
    background: "https://i.ibb.co/gbwpKVmy/blue-sky.gif",
    colour: "#738eaa",
  },
  "02n": {
    icon: "https://i.ibb.co/p6ygXMrL/cloudy-night-icon.png",
    description: "Cloudy night weather icon",
    background: "https://i.ibb.co/yn6LL3Wp/cloudy-night.gif",
    colour: "#343434",
  },
  "03d": {
    icon: "https://i.ibb.co/kVM5Wkwq/cloudy-icon.png",
    description: "A cloud (scattered cloud) weather icon",
    background: "https://i.ibb.co/4RWZggBr/scattered-clouds-day.gif",
    colour: "#143153",
  },
  "03n": {
    icon: "https://i.ibb.co/kVM5Wkwq/cloudy-icon.png",
    description: "A cloud (scattered clouds) weather icon",
    background: "ttps://i.ibb.co/5Xv5PKzc/overcast-night.gif",
    colour: "#424D50",
  },
  "04d": {
    icon: "https://i.ibb.co/YBgK3gSp/cloudy-cloud-icon.png",
    description: "Two clouds (broken clouds) weather icon",
    background: "https://i.ibb.co/YJwfLvN/overcast-day.gif",
    colour: "#7A7A7A",
  },
  "04n": {
    icon: "https://i.ibb.co/YBgK3gSp/cloudy-cloud-icon.png",
    description: "Two clouds (broken clouds) weather icon",
    background: "https://i.ibb.co/vN7rKH5/overcast-cloudy-night.gif",
    colour: "#1F1729",
  },
  "09d": {
    icon: "https://i.ibb.co/0y9WRTNF/rain-icon.png",
    description: "Rain cloud weather icon",
    background: "https://i.ibb.co/CKDDyGLJ/rainy-day.gif",
    colour: "#1F232B",
  },
  "09n": {
    icon: "https://i.ibb.co/0y9WRTNF/rain-icon.png",
    description: "Rain cloud weather icon",
    background: "https://i.ibb.co/bMTcJKsq/rainy-night.gif",
    colour: "#000000",
  },
  "10d": {
    icon: "https://i.ibb.co/ZzbCgsmj/rainy-day-icon.png",
    description: "Rain cloud with a sun weather icon",
    background: "https://i.ibb.co/CKDDyGLJ/rainy-day.gif",
    colour: "#1F232B",
  },
  "10n": {
    icon: "https://i.ibb.co/GQ3nWqSz/rainy-night-icon.png",
    description: "Rain cloud with a crescent moon weather icon",
    background: "https://i.ibb.co/bMTcJKsq/rainy-night.gif",
    colour: "#000000",
  },
  "11d": {
    icon: "https://i.ibb.co/kpdq61W/thunderstorm-day-icon.png",
    description: "Thunderstorm cloud weather icon",
    background: "https://i.ibb.co/HLZnLVDr/thunder.gif",
    colour: "#0F1E26",
  },
  "11n": {
    icon: "https://i.ibb.co/S7V0pBXg/thunderstorm-night-icon.png",
    description: "Thunderstorm cloud weather icon",
    background: "https://i.ibb.co/xqVrXJj4/thunderstorm-night.gif",
    colour: "#030312",
  },
  "13d": {
    icon: "https://i.ibb.co/FkzKbnRm/snowflake-icon.png",
    description: "A snowflake weather icon",
    background: "https://i.ibb.co/ZzpmzmYn/snow.gif",
    colour: "#383838",
  },
  "13n": {
    icon: "https://i.ibb.co/FkzKbnRm/snowflake-icon.png",
    description: "A snowflake weather icon",
    background: "https://i.ibb.co/whdSDQGG/snow-night.gif",
    colour: "#1E2327",
  },
  "50d": {
    icon: "https://i.ibb.co/8gKqgzMH/mist-icon.png",
    description: "A mist weather icon",
    background: "https://i.ibb.co/nNwVGmjQ/fog.gif",
    colour: "#2F2D2E",
  },
  "50n": {
    icon: "https://i.ibb.co/8gKqgzMH/mist-icon.png",
    description: "A mist weather icon",
    background: "https://i.ibb.co/nNwVGmjQ/fog.gif",
    colour: "#2F2D2E",
  },
};
